Start the initial draft implementation
sidilabs/kishell pull request #1
Opened 2020-11-20 19:27 UTC by edersonmf

This includes options to manage configuration as well as do simple
queries.

2020-11-20 19:35 UTC, ddmendes approved these changes

2020-11-20 19:45 UTC, robsondepaula approved these changes
LGTM!

2020-11-24 18:45 UTC, ddmendes requested changes
Very good. There is just some minor details.

2020-11-24 18:45 UTC, ddmendes commented on pkg/config/file.go
> +  byteValue, _ := ioutil.ReadAll(jsonFile)
The `defer jsonFile.Close()` should be the first thing after checking file errors. So past error checking you always guarantee the file will be closed.

2020-11-24 18:45 UTC, ddmendes commented on pkg/config/file.go
> +  err = json.Unmarshal(byteValue, &configFile)
This is not wrong but there's another approach for Unmarshaling. Once os.File has the Read() method then it implements io.Reader. Thus you can use
```suggestion
  err = json.NewDecoder(jsonFile).Decode(&configFile)
```
and save the file reading segment. But it's up to you. Both approaches are right.

2020-11-24 18:45 UTC, ddmendes commented on pkg/options/configure_option.go
> +  if len(configFile.CurrentServer) <=  0 || len(defaultServer) <= 0 || defaultServer == "Y" {
You could also expect for `"y"`

2020-11-24 18:45 UTC, ddmendes commented on pkg/options/configure_option.go
> +  if len(configFile.CurrentRole) <=  0 || len(defaultRole) <= 0 || defaultRole == "Y" {
You could also expect for `"y"`

2020-11-24 18:45 UTC, ddmendes commented on pkg/options/use_option.go
> +func (u *UseCmd) Run(ctx *Context) error {
We could validate if Server/Role exists in the configuration before setting it as default

2020-11-24 18:45 UTC, ddmendes commented on pkg/options/search_option.go
> +   server = ctx.ConfigFile.Servers[s.Server]
You could easily check Server existence by
```suggestion
   server, ok = ctx.ConfigFile.Servers[s.Server]
   if !ok {
       return fmt.Errorf("Server %s does not exist", s.Server)
   }
```

2020-11-24 20:10 UTC, merged